openai:
  timeout: 10 #in seconds
resilience4j:
  circuitbreaker:
    instances:
      message-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 80
        waitDurationInOpenState: 60000ms
  bulkhead:
    instances:
      message-service:
        maxConcurrentCalls: 1
        maxWaitDuration: 1000ms
  retry:
    instances:
      message-service:
        maxRetryAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      message-service:
        max-concurrent-calls: 3
        max-wait-duration: 1s