server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
openai:
  key: key
  timeout: 10 #in seconds

resilience4j:
  circuitbreaker:
    instances:
      message-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 80
        waitDurationInOpenState: 60000ms
  bulkhead:
    instances:
      message-service:
        maxConcurrentCalls: 1
        maxWaitDuration: 1000ms
  retry:
    instances:
      message-service:
        maxRetryAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      message-service:
        max-concurrent-calls: 3
        max-wait-duration: 1s