spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
resilience4j:
  circuitbreaker:
    instances:
      botuser-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 80
        waitDurationInOpenState: 60000ms
  bulkhead:
    instances:
      botuser-service:
        maxConcurrentCalls: 1
        maxWaitDuration: 1000ms
  retry:
    instances:
      botuser-service:
        maxRetryAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      botuser-service:
        max-concurrent-calls: 3
        max-wait-duration: 1s
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0