server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: 
    password:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

telegram:
  bot:
    username: Denysenko_telegram_openai_bot
    token:
resilience4j:
  circuitbreaker:
    instances:
      botuser-service:
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        slowCallDurationThreshold: 1000ms
        slowCallRateThreshold: 80
        waitDurationInOpenState: 60000ms
  bulkhead:
    instances:
      botuser-service:
        maxConcurrentCalls: 1
        maxWaitDuration: 1000ms
  retry:
    instances:
      botuser-service:
        maxRetryAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      botuser-service:
        max-concurrent-calls: 3
        max-wait-duration: 1s