server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\Learning\Others\TelegramOpenAPIProject_Microservices\config-service\src\main\resources\config

